import{i as c,a as q,S as v}from"./assets/vendor-5401a4b0.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const u of n.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function i(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(r){if(r.ep)return;r.ep=!0;const n=i(r);fetch(r.href,n)}})();const f=document.querySelector(".form"),p=document.querySelector(".gallery"),E=document.querySelector("div"),I=document.querySelector("input"),m=document.querySelector(".btn-load"),y=()=>{const t=document.createElement("span");t.classList.add("loader"),E.append(t)},l=()=>{const t=document.querySelector(".loader");t&&t.remove()},$=()=>{m.style.display="block"},d=()=>{m.style.display="none"};let h=1,g=15,a=" ",b;f.addEventListener("submit",async t=>{if(h=1,y(),p.innerHTML=" ",t.preventDefault(),a=e.target.elements.query.value.trim(),!a){S("Empty field");return}try{a=I.value;const o=await w();L(o),f.reset(),l(),$(),o.hits.length<15&&d(),o.hits.length===0&&(d(),c.error({message:"Sorry, there are no images matching <br>your search query. Please try again!</br>",position:"center",transitionIn:"fadeInLeft"}))}catch{c.error({title:"Error"})}});m.addEventListener("click",async()=>{y();try{h+=1;const t=await w();L(t),l();const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),(p.children.length>=b||t.hits.length<g)&&(c.warning({message:"We are sorry, but you have reached the end of search results.",position:"bottomCenter",transitionIn:"fadeInDown"}),d())}catch{c.error({title:"Error"}),l()}if(!a){S("empty field");return}});async function w(){try{const t="42318404-1173ca802dc215ae825a9e5c8",o=new URLSearchParams({key:t,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:h,per_page:g}),i=await q.get(`https://pixabay.com/api/?${o}`);return b=i.data.totalHits,i.data}catch(t){throw console.log(t),WebTransportError}}function L(t){const o=t.hits.map(s=>`
            <li class="gallery-item"><a href="${s.largeImageURL}">
          <img class="gallery-image" src="${s.webformatURL}" alt="${s.tags}"></a>
          <p><b>Likes: </b>${s.likes}</p>
          <p><b>Views: </b>${s.views}</p>
          <p><b>Comments: </b>${s.comments}</p>
          <p><b>Downloads: </b>${s.downloads}</p>
          </li>`).join("");p.insertAdjacentHTML("beforeend",o),new v(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",fadeSpeed:150,captionSelector:"img",captionDelay:250}).on("show.simplelightbox").refresh(),l()}function S(t){c.error({title:"Error",message:t})}
//# sourceMappingURL=commonHelpers.js.map
