import{i,a as S,S as q}from"./assets/vendor-5401a4b0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const h=document.querySelector(".form"),p=document.querySelector(".gallery"),v=document.querySelector("div"),E=document.querySelector("input"),u=document.querySelector(".btn-load"),f=()=>{const e=document.createElement("span");e.classList.add("loader"),v.append(e)},a=()=>{const e=document.querySelector(".loader");e&&e.remove()},I=()=>{u.style.display="block"},d=()=>{u.style.display="none"};let m=1,y=15,c=" ",g;h.addEventListener("submit",async e=>{if(m=1,f(),p.innerHTML=" ",e.preventDefault(),!c){L("Empty field");return}try{c=E.value;const r=await b();w(r),h.reset(),a(),I(),r.hits.length<15&&d(),r.hits.length===0&&(d(),i.error({message:"Sorry, there are no images matching <br>your search query. Please try again!</br>",position:"center",transitionIn:"fadeInLeft"}))}catch{i.error({title:"Error"})}});u.addEventListener("click",async()=>{f();try{m+=1;const e=await b();w(e),a();const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),(p.children.length>=g||e.hits.length<y)&&(i.warning({message:"We are sorry, but you have reached the end of search results.",position:"bottomCenter",transitionIn:"fadeInDown"}),d())}catch{i.error({title:"Error"}),a()}if(!c){L("empty field");return}});async function b(){try{const e="42318404-1173ca802dc215ae825a9e5c8",r=new URLSearchParams({key:e,q:c,image_type:"photo",orientation:"horizontal",safesearch:!0,page:m,per_page:y}),s=await S.get(`https://pixabay.com/api/?${r}`);return g=s.data.totalHits,s.data}catch(e){throw console.log(e),WebTransportError}}function w(e){const r=e.hits.map(n=>`
            <li class="gallery-item"><a href="${n.largeImageURL}">
          <img class="gallery-image" src="${n.webformatURL}" alt="${n.tags}"></a>
          <p><b>Likes: </b>${n.likes}</p>
          <p><b>Views: </b>${n.views}</p>
          <p><b>Comments: </b>${n.comments}</p>
          <p><b>Downloads: </b>${n.downloads}</p>
          </li>`).join("");p.insertAdjacentHTML("beforeend",r),new q(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",fadeSpeed:150,captionSelector:"img",captionDelay:250}).on("show.simplelightbox").refresh(),a()}function L(e){i.error({title:"Error",message:e})}
//# sourceMappingURL=commonHelpers.js.map
